//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyIncomeTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AwrynTasksName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AwrynTasksName"]));
            }
            set {
                this["AwrynTasksName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AlexanderTasksName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AlexanderTasksName"]));
            }
            set {
                this["AlexanderTasksName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ArwynTasksDate {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ArwynTasksDate"]));
            }
            set {
                this["ArwynTasksDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AlexanderTasksDate {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AlexanderTasksDate"]));
            }
            set {
                this["AlexanderTasksDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ArwynTasksTime {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ArwynTasksTime"]));
            }
            set {
                this["ArwynTasksTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AlexanderTasksTime {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AlexanderTasksTime"]));
            }
            set {
                this["AlexanderTasksTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AlexanderPayedAmount {
            get {
                return ((float)(this["AlexanderPayedAmount"]));
            }
            set {
                this["AlexanderPayedAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AlexanderAddedAmount {
            get {
                return ((float)(this["AlexanderAddedAmount"]));
            }
            set {
                this["AlexanderAddedAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ArwynPayedAmount {
            get {
                return ((float)(this["ArwynPayedAmount"]));
            }
            set {
                this["ArwynPayedAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ArwynAddedAmount {
            get {
                return ((float)(this["ArwynAddedAmount"]));
            }
            set {
                this["ArwynAddedAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSave {
            get {
                return ((string)(this["LastSave"]));
            }
            set {
                this["LastSave"] = value;
            }
        }
    }
}
